GET http://172.16.215.64:5000/api/cv HTTP/1.1


###

GET http://172.16.215.64:5000/api/cv/2 HTTP/1.1

###

POST http://172.16.215.64:5000/api/cv HTTP/1.1
Content-Type: application/json

{"name":"henry"}

###

PUT http://172.16.215.64:5000/api/cv/2 HTTP/1.1
Content-Type: application/json

{"name":"naja"}

###

DELETE http://172.16.215.64:5000/api/cv/11 HTTP/1.1
Content-Type: application/json


###

POST http://172.16.215.64:5000/api/cv/all HTTP/1.1
Content-Type: application/json

{"a":"naja","b":"123"}

